### ISSUE TITLE
Move planner to be a SMACH state

### ISSUE THREAD

**Issue by margocrawf** [olin-robotic-sailing/oars-roboboat#11]

**Comment by HALtheWise** [comment]
An example of a SMACH-based behavior engine from RoboSys is here.
https://github.com/RoboSys-Alphabot/brain/blob/master/alpha_main/scripts/state_machine/states.py

![screenshot from 2017-03-29 14-35-16](https://cloud.githubusercontent.com/assets/1697528/24470453/f76bb422-148c-11e7-8454-b740bf37a8f8.png)

**Comment by HALtheWise** [comment]
SMACH is the ROS state machine library
http://wiki.ros.org/smach
