### ISSUE TITLE
Arduino code for four motor control

### ISSUE THREAD

**Issue by zneb97** [olin-robotic-sailing/oars-roboboat#12]
Writing arduino code to control the motors on jankboat. Use servo object to writeMicroseconds to control via PWM

**Comment by HALtheWise** [comment]
Current code from tugboat is [here](https://github.com/olin-robotic-sailing/oars-roboboat/blob/master/arduino_code/tugboat_teensy/tugboat_teensy.ino)

**Comment by HALtheWise** [comment]
https://github.com/olin-robotic-sailing/oars-roboboat/blob/master/ros_topics.md

**Comment by zneb97** [comment]
Pushed to arduino_code/jankboat. Code is currently untested.
